---
- name: Converge
  hosts: all
  vars:
    admin_user: "molecule"
  tasks:
    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        shell: /bin/bash
        state: present

    - name: "Include jupyter"
      include_role:
        name: "jupyter"
